server:
  port: 8000

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=library
    username: badbug
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:

management:
  security:
    enabled: false